# Generated by Django 6.0.1 on 2026-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='has_decoration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_dj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_makeup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_photography',
            field=models.BooleanField(default=False),
        ),
    ]
