# Generated by Django 6.0.1 on 2026-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Birthday', 'Birthday'), ('Social', 'Social Gathering'), ('Other', 'Other')], default='Wedding', max_length=50),
        ),
    ]
