# Generated by Django 6.0.1 on 2026-02-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hall_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='event_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Birthday', 'Birthday'), ('Social', 'Social Gathering'), ('Other', 'Other')], default='Wedding', max_length=50, null=True),
        ),
    ]
