# Generated by Django 6.0.1 on 2026-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_hall_event_types_hall_google_maps_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=3),
        ),
    ]
