# Generated by Django 6.0.1 on 2026-04-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_hall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='decoration_price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall',
            name='dj_price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall',
            name='makeup_price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall',
            name='photography_price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall',
            name='price_per_plate',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
