# Generated by Django 6.0.1 on 2026-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_hallimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='menu',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
